# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = example.pdf

# List the files included in the slides
DEPS =

# Relative path to the LaTeX koala documentclass setup files
# You should not need to touch this
RELPATH = /home/db0/dev/Life-is-FullEIP/doc/template/

# You should not touch this either
include $(RELPATH)/Makefile.LaTeX
