# List the pdf's to build. foo.tex will produce foo.pdf
TARGETS = foo.pdf

# List the files included in the slides
DEPS = somePicture.png someSound.flac someOtherPicture.png

# Relative path to the LaTeX life documentclass setup files
RELPATH = /home/db0/dev/Life-is-FullEIP

# You should not touch this either
include $(RELPATH)/Makefile.LaTeX
